"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { CoverageGrades } from "./CoverageGrades";
import { jsPDF } from "jspdf";
import toast from "react-hot-toast";

interface ScriptCoverageOutputProps {
  streamedText: string;
  isGenerating: boolean;
  scriptTitle: string;
  scriptType: string;
  focusAreas: string[];
  coverageDepth: string;
}

export function ScriptCoverageOutput({
  streamedText,
  isGenerating,
  scriptTitle,
  scriptType,
  focusAreas,
  coverageDepth,
}: ScriptCoverageOutputProps) {
  const [showSaveModal, setShowSaveModal] = useState(false);
  const [userNote, setUserNote] = useState("");
  const [isSaving, setIsSaving] = useState(false);
  const [showSceneBreakdown, setShowSceneBreakdown] = useState(false);

  // Helper to parse JSON from tag
  const parseTag = (startTag: string, endTag: string) => {
    const startIdx = streamedText.indexOf(startTag);
    if (startIdx === -1) return null;
    const endIdx = streamedText.indexOf(endTag, startIdx + startTag.length);
    const content = streamedText.slice(
      startIdx + startTag.length,
      endIdx === -1 ? undefined : endIdx
    ).trim();

    try {
      const cleanJson = content.replace(/^```json\s*|```$/g, "").trim();
      return JSON.parse(cleanJson);
    } catch {
      // Attempt to return a partial parse or just return null
      return null;
    }
  };

  const report = {
    logline_premise: parseTag("[LOGLINE_PREMISE]", "[END_LOGLINE_PREMISE]"),
    coverage_grades: parseTag("[COVERAGE_GRADES]", "[END_COVERAGE_GRADES]"),
    strengths: parseTag("[STRENGTHS]", "[END_STRENGTHS]"),
    weaknesses: parseTag("[WEAKNESSES]", "[END_WEAKNESSES]"),
    scene_breakdown: parseTag("[SCENE_BREAKDOWN]", "[END_SCENE_BREAKDOWN]"),
    dialogue_samples: parseTag("[DIALOGUE_SAMPLES]", "[END_DIALOGUE_SAMPLES]"),
    recommendations: parseTag("[RECOMMENDATIONS]", "[END_RECOMMENDATIONS]"),
    verdict: parseTag("[VERDICT]", "[END_VERDICT]"),
  };

  const isDialogueIncluded = focusAreas.includes("Dialogue");

  // Export as PDF using jsPDF
  const handleExportPDF = () => {
    try {
      const doc = new jsPDF();
      let yOffset = 20;

      // Helper to add page if offset exceeds margin
      const checkPageBreak = (neededHeight: number = 20) => {
        if (yOffset + neededHeight > 280) {
          doc.addPage();
          // Draw watermark
          doc.saveGraphicsState();
          doc.setFontSize(40);
          doc.setTextColor(240, 240, 240);
          doc.setFont("Courier", "bold");
          doc.text("TRACK REFRAME AI", 35, 150, { angle: 45 });
          doc.restoreGraphicsState();
          yOffset = 20;
        }
      };

      // Cover Page
      doc.saveGraphicsState();
      doc.setFontSize(40);
      doc.setTextColor(240, 240, 240);
      doc.setFont("Courier", "bold");
      doc.text("TRACK REFRAME AI", 35, 150, { angle: 45 });
      doc.restoreGraphicsState();

      doc.setFont("Courier", "bold");
      doc.setFontSize(28);
      doc.setTextColor(10, 10, 15);
      doc.text("SCRIPT COVERAGE REPORT", 20, 60);

      doc.setFont("Helvetica", "normal");
      doc.setFontSize(16);
      doc.setTextColor(100, 100, 100);
      doc.text(`Title: ${scriptTitle || "Untitled Script"}`, 20, 80);
      doc.text(`Type: ${scriptType}`, 20, 90);
      doc.text(`Depth: ${coverageDepth}`, 20, 100);
      doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 110);

      doc.setFontSize(10);
      doc.text("Generated by Track Reframe Studio AI", 20, 270);
      doc.addPage();

      yOffset = 20;

      // Section 1: Logline & Premise
      if (report.logline_premise) {
        doc.setFont("Helvetica", "bold");
        doc.setFontSize(14);
        doc.text("1. LOGLINE & PREMISE", 20, yOffset);
        yOffset += 10;
        doc.setFont("Helvetica", "oblique");
        doc.setFontSize(11);
        const loglineLines = doc.splitTextToSize(`Logline: "${report.logline_premise.logline}"`, 170);
        doc.text(loglineLines, 20, yOffset);
        yOffset += loglineLines.length * 6 + 4;

        doc.setFont("Helvetica", "bold");
        doc.text(`Premise Strength: ${report.logline_premise.premise_strength}`, 20, yOffset);
        yOffset += 6;
        doc.setFont("Helvetica", "normal");
        const premiseLines = doc.splitTextToSize(report.logline_premise.premise_explanation, 170);
        doc.text(premiseLines, 20, yOffset);
        yOffset += premiseLines.length * 6 + 10;
      }

      checkPageBreak(60);

      // Section 2: Coverage Grades
      if (report.coverage_grades) {
        doc.setFont("Helvetica", "bold");
        doc.setFontSize(14);
        doc.text("2. COVERAGE GRADES", 20, yOffset);
        yOffset += 10;
        doc.setFont("Helvetica", "bold");
        doc.setFontSize(11);
        doc.text(`Overall Grade: ${report.coverage_grades.overall}`, 20, yOffset);
        yOffset += 8;

        const grades = [
          ["Story Structure", report.coverage_grades.story_structure],
          ["Character Dev", report.coverage_grades.character_development],
          ["Dialogue", report.coverage_grades.dialogue],
          ["Pacing", report.coverage_grades.pacing],
          ["Theme & Subtext", report.coverage_grades.theme_subtext],
          ["Originality", report.coverage_grades.originality],
          ["Commercial Viability", report.coverage_grades.commercial_viability],
        ];

        grades.forEach(([name, grade]) => {
          doc.setFont("Helvetica", "normal");
          doc.text(`${name}:`, 20, yOffset);
          doc.setFont("Helvetica", "bold");
          doc.text(grade || "N/A", 80, yOffset);
          yOffset += 6;
          checkPageBreak(10);
        });
        yOffset += 4;
      }

      checkPageBreak(40);

      // Section 3: Strengths
      if (report.strengths) {
        doc.setFont("Helvetica", "bold");
        doc.setFontSize(14);
        doc.text("3. STRENGTHS", 20, yOffset);
        yOffset += 10;
        doc.setFont("Helvetica", "normal");
        doc.setFontSize(11);
        report.strengths.forEach((strength: string, i: number) => {
          const strengthLines = doc.splitTextToSize(`- ${strength}`, 170);
          doc.text(strengthLines, 20, yOffset);
          yOffset += strengthLines.length * 6 + 2;
          checkPageBreak(15);
        });
        yOffset += 6;
      }

      checkPageBreak(40);

      // Section 4: Weaknesses
      if (report.weaknesses) {
        doc.setFont("Helvetica", "bold");
        doc.setFontSize(14);
        doc.text("4. WEAKNESSES", 20, yOffset);
        yOffset += 10;
        doc.setFont("Helvetica", "normal");
        doc.setFontSize(11);
        report.weaknesses.forEach((weakness: any, i: number) => {
          doc.setFont("Helvetica", "bold");
          doc.text(`${i + 1}. ${weakness.title}`, 20, yOffset);
          yOffset += 6;
          doc.setFont("Helvetica", "normal");
          const explanationLines = doc.splitTextToSize(weakness.explanation, 170);
          doc.text(explanationLines, 20, yOffset);
          yOffset += explanationLines.length * 6 + 4;
          checkPageBreak(25);
        });
        yOffset += 6;
      }

      checkPageBreak(40);

      // Section 5: Scene Breakdown
      if (report.scene_breakdown) {
        doc.setFont("Helvetica", "bold");
        doc.setFontSize(14);
        doc.text("5. SCENE BREAKDOWN", 20, yOffset);
        yOffset += 10;
        doc.setFont("Helvetica", "normal");
        doc.setFontSize(10);
        report.scene_breakdown.forEach((scene: any) => {
          const sceneText = `Scene ${scene.scene_num} [${scene.grade}]: ${scene.heading} - ${scene.note}`;
          const sceneLines = doc.splitTextToSize(sceneText, 170);
          doc.text(sceneLines, 20, yOffset);
          yOffset += sceneLines.length * 5 + 2;
          checkPageBreak(15);
        });
        yOffset += 6;
      }

      checkPageBreak(40);

      // Section 6: Dialogue
      if (report.dialogue_samples && isDialogueIncluded) {
        doc.setFont("Helvetica", "bold");
        doc.setFontSize(14);
        doc.text("6. DIALOGUE SAMPLES", 20, yOffset);
        yOffset += 10;
        doc.setFont("Courier", "normal");
        doc.setFontSize(10);
        report.dialogue_samples.forEach((sample: any) => {
          doc.setFont("Courier", "bold");
          doc.text(sample.character, 40, yOffset);
          yOffset += 5;
          doc.setFont("Courier", "oblique");
          const dialogLines = doc.splitTextToSize(sample.dialogue, 130);
          doc.text(dialogLines, 40, yOffset);
          yOffset += dialogLines.length * 5 + 4;
          doc.setFont("Helvetica", "normal");
          doc.setFontSize(9);
          const noteLines = doc.splitTextToSize(`Note: ${sample.note} (${sample.strength})`, 150);
          doc.text(noteLines, 20, yOffset);
          yOffset += noteLines.length * 5 + 6;
          doc.setFont("Courier", "normal");
          doc.setFontSize(10);
          checkPageBreak(25);
        });
        yOffset += 6;
      }

      checkPageBreak(40);

      // Section 7: Recommendations
      if (report.recommendations) {
        doc.setFont("Helvetica", "bold");
        doc.setFontSize(14);
        doc.text("7. RECOMMENDATIONS", 20, yOffset);
        yOffset += 10;
        doc.setFont("Helvetica", "normal");
        doc.setFontSize(11);
        report.recommendations.forEach((rec: any, i: number) => {
          doc.setFont("Helvetica", "bold");
          doc.text(`${i + 1}. ${rec.title}`, 20, yOffset);
          yOffset += 6;
          doc.setFont("Helvetica", "normal");
          const recLines = doc.splitTextToSize(rec.explanation, 170);
          doc.text(recLines, 20, yOffset);
          yOffset += recLines.length * 6 + 4;
          checkPageBreak(25);
        });
        yOffset += 6;
      }

      checkPageBreak(40);

      // Section 8: Verdict
      if (report.verdict) {
        doc.setFont("Helvetica", "bold");
        doc.setFontSize(14);
        doc.text("8. FINAL VERDICT", 20, yOffset);
        yOffset += 10;
        doc.setFont("Helvetica", "bold");
        doc.setFontSize(14);
        doc.text(`VERDICT: ${report.verdict.verdict}`, 20, yOffset);
        yOffset += 10;
        doc.setFont("Helvetica", "normal");
        doc.setFontSize(11);
        const verdictLines = doc.splitTextToSize(report.verdict.verdict_narrative, 170);
        doc.text(verdictLines, 20, yOffset);
      }

      doc.save(`${scriptTitle.replace(/\s+/g, "_") || "Script"}_AI_Coverage.pdf`);
      toast.success("PDF exported successfully!");
    } catch (err: any) {
      console.error(err);
      toast.error("Failed to export PDF: " + err.message);
    }
  };

  const handleCopyReport = () => {
    navigator.clipboard.writeText(streamedText);
    toast.success("Full report copied to clipboard!");
  };

  const handleSaveReport = async () => {
    setIsSaving(true);
    try {
      const overallGrade = report.coverage_grades?.overall || "C";
      const res = await fetch("/api/ai/script-coverage/save", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          scriptTitle: scriptTitle || "Untitled Script",
          scriptType,
          coverageDepth,
          overallGrade,
          reportJson: report,
          userNote,
        }),
      });

      if (!res.ok) {
        const error = await res.json();
        throw new Error(error.error || "Failed to save");
      }

      toast.success("Coverage report saved successfully!");
      setShowSaveModal(false);
    } catch (err: any) {
      toast.error(err.message);
    } finally {
      setIsSaving(false);
    }
  };

  if (!streamedText) return null;

  return (
    <div className="space-y-8 mt-12 w-full max-w-[800px] mx-auto">
      <div className="rounded-2xl border border-indigo/20 bg-[#111118] p-6 md:p-8 shadow-xl space-y-8 relative overflow-hidden">
        {/* Decorative film strip sprocket border at the top */}
        <div className="absolute top-0 left-0 right-0 h-3 film-strip-border opacity-30" />

        {/* Output Header */}
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 pt-2 border-b border-white/5 pb-4">
          <div className="flex items-center gap-3">
            <span className="px-3 py-1 rounded-full bg-indigo/15 border border-indigo/30 text-indigo text-xs font-bold">
              ✦ AI Coverage Report
            </span>
            <span className="px-3 py-1 rounded-full bg-amber/10 border border-amber/20 text-amber text-xs font-semibold">
              {scriptType}
            </span>
          </div>
          <span className="text-xs text-text-muted">
            Generated {new Date().toLocaleTimeString()}
          </span>
        </div>

        {/* Section 1: Logline & Premise */}
        {report.logline_premise ? (
          <div className="space-y-4">
            <h3 className="text-sm font-mono tracking-[0.2em] text-amber uppercase">Logline & Premise</h3>
            <div className="space-y-3 bg-[#0d0d12] p-4 rounded-xl border border-white/5">
              <div>
                <span className="text-[11px] uppercase tracking-wider text-text-muted font-bold block mb-1">
                  AI-Generated Logline
                </span>
                <p className="text-base text-white italic">
                  "{report.logline_premise.logline}"
                </p>
              </div>
              <div className="pt-2 border-t border-white/5 flex items-center gap-3">
                <span className="text-xs font-bold text-text-secondary">Premise Strength:</span>
                <span
                  className={`px-2.5 py-0.5 rounded-full text-xs font-extrabold ${
                    report.logline_premise.premise_strength === "Excellent"
                      ? "bg-emerald-500/15 text-emerald-400 border border-emerald-500/20"
                      : report.logline_premise.premise_strength === "Strong"
                      ? "bg-teal-500/15 text-teal-400 border border-teal-500/20"
                      : report.logline_premise.premise_strength === "Fair"
                      ? "bg-amber-500/15 text-amber border border-amber-500/20"
                      : "bg-red-500/15 text-red-400 border border-red-500/20"
                  }`}
                >
                  {report.logline_premise.premise_strength}
                </span>
              </div>
              <p className="text-sm text-text-secondary leading-relaxed">
                {report.logline_premise.premise_explanation}
              </p>
            </div>
          </div>
        ) : (
          <div className="animate-pulse space-y-3">
            <div className="h-4 w-32 bg-white/5 rounded" />
            <div className="h-20 bg-white/5 rounded-xl" />
          </div>
        )}

        {/* Section 2: Grades & Overall Grade */}
        {report.coverage_grades ? (
          <div className="space-y-6">
            <CoverageGrades grades={report.coverage_grades} />

            {/* Overall Grade card */}
            <div className="bg-[#1e1e2d] border border-amber/30 p-6 rounded-xl text-center space-y-2 relative overflow-hidden flex flex-col items-center">
              <span className="text-xs font-mono uppercase tracking-[0.2em] text-amber">
                Overall Grade
              </span>
              <h2 className="text-7xl font-bold font-mono tracking-tight text-amber">
                {report.coverage_grades.overall}
              </h2>
              <p className="text-sm text-text-secondary max-w-md mx-auto pt-2">
                {report.coverage_grades.overall_explanation}
              </p>
            </div>
          </div>
        ) : (
          <div className="animate-pulse space-y-4">
            <div className="h-4 w-40 bg-white/5 rounded" />
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              {[...Array(8)].map((_, i) => (
                <div key={i} className="h-24 bg-white/5 rounded-xl" />
              ))}
            </div>
          </div>
        )}

        {/* Section 3: Strengths */}
        {report.strengths ? (
          <div className="space-y-3">
            <h3 className="text-sm font-mono tracking-[0.2em] text-emerald-400 uppercase flex items-center gap-2">
              <span>✓</span> What's Working
            </h3>
            <ul className="space-y-2">
              {report.strengths.map((strength: string, i: number) => (
                <motion.li
                  key={i}
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: i * 0.1 }}
                  className="flex items-start gap-3 text-sm text-text-primary leading-relaxed"
                >
                  <span className="text-amber">—</span>
                  <span>{strength}</span>
                </motion.li>
              ))}
            </ul>
          </div>
        ) : (
          <div className="animate-pulse space-y-2">
            <div className="h-4 w-36 bg-white/5 rounded" />
            <div className="h-16 bg-white/5 rounded-xl" />
          </div>
        )}

        {/* Section 4: Weaknesses */}
        {report.weaknesses ? (
          <div className="space-y-4">
            <h3 className="text-sm font-mono tracking-[0.2em] text-red-400 uppercase flex items-center gap-2">
              <span>⚠</span> What Needs Work
            </h3>
            <div className="space-y-3">
              {report.weaknesses.map((weakness: any, i: number) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.1 }}
                  className="bg-[#1e1414]/30 border border-red-500/10 p-4 rounded-xl space-y-1"
                >
                  <h4 className="text-sm font-bold text-white flex items-center gap-2">
                    <span className="text-red-500">•</span> {weakness.title}
                  </h4>
                  <p className="text-xs text-text-secondary leading-relaxed pl-4">
                    {weakness.explanation}
                  </p>
                </motion.div>
              ))}
            </div>
          </div>
        ) : (
          <div className="animate-pulse space-y-2">
            <div className="h-4 w-40 bg-white/5 rounded" />
            <div className="h-20 bg-white/5 rounded-xl" />
          </div>
        )}

        {/* Section 5: Scene-by-Scene Breakdown */}
        {report.scene_breakdown ? (
          <div className="space-y-3">
            <button
              onClick={() => setShowSceneBreakdown(!showSceneBreakdown)}
              className="w-full flex items-center justify-between p-4 bg-[#0d0d12] hover:bg-[#15151e] border border-white/5 rounded-xl transition-all group"
            >
              <span className="text-sm font-mono tracking-[0.1em] text-amber uppercase font-semibold">
                Scene-by-Scene Breakdown
              </span>
              <span className="text-xs text-text-secondary group-hover:text-amber transition-colors">
                {showSceneBreakdown ? "Hide ▴" : "View Scene Breakdown ▾"}
              </span>
            </button>

            <AnimatePresence>
              {showSceneBreakdown && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: "auto" }}
                  exit={{ opacity: 0, height: 0 }}
                  className="overflow-hidden border border-white/5 rounded-xl bg-[#0d0d12]/50 divide-y divide-white/5"
                >
                  {report.scene_breakdown.map((scene: any, idx: number) => {
                    const lowGrade = ["C", "D", "F"].includes(scene.grade);
                    return (
                      <div
                        key={idx}
                        className={`p-4 flex flex-col md:flex-row md:items-center gap-4 justify-between ${
                          lowGrade ? "border-l-4 border-l-red-500/40" : ""
                        }`}
                      >
                        <div className="space-y-1">
                          <div className="flex items-center gap-3">
                            <span className="text-xs font-mono text-text-muted">
                              Scene #{scene.scene_num}
                            </span>
                            <span className="font-mono text-xs text-white uppercase bg-white/5 px-2 py-0.5 rounded">
                              {scene.heading}
                            </span>
                          </div>
                          <p className="text-xs text-text-secondary leading-relaxed">
                            {scene.note}
                          </p>
                        </div>
                        <div
                          className={`w-8 h-8 rounded-full border flex items-center justify-center font-bold text-xs font-mono shrink-0 self-start md:self-auto ${
                            scene.grade === "A"
                              ? "bg-emerald-500/10 border-emerald-500/20 text-emerald-400"
                              : scene.grade === "B"
                              ? "bg-teal-500/10 border-teal-500/20 text-teal-400"
                              : "bg-amber-500/10 border-amber-500/20 text-amber"
                          }`}
                        >
                          {scene.grade}
                        </div>
                      </div>
                    );
                  })}
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        ) : (
          <div className="animate-pulse h-12 bg-white/5 rounded-xl" />
        )}

        {/* Section 6: Dialogue Samples */}
        {report.dialogue_samples && isDialogueIncluded && (
          <div className="space-y-4">
            <h3 className="text-sm font-mono tracking-[0.2em] text-amber uppercase">
              Dialogue Analysis
            </h3>
            <div className="grid grid-cols-1 gap-4">
              {report.dialogue_samples.map((sample: any, idx: number) => (
                <div
                  key={idx}
                  className="bg-[#0d0d12] p-5 rounded-xl border border-white/5 relative overflow-hidden flex flex-col justify-between space-y-4"
                >
                  <span
                    className={`absolute top-3 right-3 px-2 py-0.5 rounded text-[10px] font-bold ${
                      sample.strength === "Strong"
                        ? "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20"
                        : "bg-amber-500/10 text-amber border border-amber-500/20"
                    }`}
                  >
                    {sample.strength}
                  </span>
                  <div className="space-y-2 border-l-2 border-amber/30 pl-4 py-1">
                    <span className="text-xs font-bold text-amber tracking-wider block">
                      {sample.character}
                    </span>
                    <p className="font-mono text-xs text-text-primary italic leading-relaxed whitespace-pre-wrap">
                      {sample.dialogue}
                    </p>
                  </div>
                  <p className="text-[11px] text-text-muted leading-relaxed pt-2 border-t border-white/5">
                    {sample.note}
                  </p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Section 7: Recommendations */}
        {report.recommendations ? (
          <div className="space-y-4">
            <h3 className="text-sm font-mono tracking-[0.2em] text-amber uppercase">
              Recommendations
            </h3>
            <div className="space-y-3">
              {report.recommendations.map((rec: any, idx: number) => (
                <div key={idx} className="flex gap-4">
                  <div className="w-6 h-6 rounded-full bg-amber/10 text-amber border border-amber/20 font-mono text-xs font-bold flex items-center justify-center shrink-0">
                    {idx + 1}
                  </div>
                  <div className="space-y-1">
                    <h4 className="text-sm font-bold text-white">{rec.title}</h4>
                    <p className="text-xs text-text-secondary leading-relaxed">
                      {rec.explanation}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        ) : (
          <div className="animate-pulse space-y-2">
            <div className="h-4 w-32 bg-white/5 rounded" />
            <div className="h-24 bg-white/5 rounded-xl" />
          </div>
        )}

        {/* Section 8: Verdict */}
        {report.verdict ? (
          <div className="border-l-4 border-l-amber bg-[#1e1e2d]/30 p-6 rounded-r-xl space-y-4">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <h3 className="font-display text-xl font-bold text-white">Reader's Verdict</h3>
              <span
                className={`px-4 py-1.5 rounded-full text-sm font-extrabold tracking-widest ${
                  report.verdict.verdict === "RECOMMEND"
                    ? "bg-emerald-500/20 text-emerald-400 border border-emerald-500/30"
                    : report.verdict.verdict === "CONSIDER"
                    ? "bg-amber-500/20 text-amber border border-amber-500/30"
                    : "bg-red-500/20 text-red-400 border border-red-500/30"
                }`}
              >
                {report.verdict.verdict}
              </span>
            </div>
            <div className="text-xs text-text-secondary leading-relaxed whitespace-pre-line space-y-3">
              {report.verdict.verdict_narrative}
            </div>
            <p className="text-[10px] text-text-muted italic pt-4 border-t border-white/5">
              This coverage was generated by Track Reframe AI. Treat it as a thoughtful first reader, not a final judgment.
            </p>
          </div>
        ) : (
          <div className="animate-pulse h-32 bg-white/5 rounded-xl" />
        )}

        {/* Action Bar */}
        {!isGenerating && (
          <div className="flex flex-wrap items-center gap-3 pt-6 border-t border-white/5">
            <button
              onClick={handleExportPDF}
              className="flex-1 min-w-[140px] h-11 rounded-lg border border-white/10 hover:border-amber/30 text-xs font-semibold text-text-secondary hover:text-white flex items-center justify-center gap-2 hover:bg-white/[0.02] active:scale-[0.98] transition-all cursor-pointer"
            >
              <span>↓</span> Download as PDF
            </button>
            <button
              onClick={handleCopyReport}
              className="flex-1 min-w-[140px] h-11 rounded-lg border border-white/10 hover:border-amber/30 text-xs font-semibold text-text-secondary hover:text-white flex items-center justify-center gap-2 hover:bg-white/[0.02] active:scale-[0.98] transition-all cursor-pointer"
            >
              <span>📋</span> Copy Report
            </button>
            <button
              onClick={() => setShowSaveModal(true)}
              className="flex-1 min-w-[140px] h-11 rounded-lg bg-amber hover:bg-amber-hover text-surface text-xs font-bold flex items-center justify-center gap-2 active:scale-[0.98] transition-all cursor-pointer"
            >
              <span>💾</span> Save to My Scripts
            </button>
          </div>
        )}
      </div>

      {/* Save Modal */}
      <AnimatePresence>
        {showSaveModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/80 backdrop-blur-md p-4">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="w-full max-w-md bg-surface border border-white/10 rounded-2xl p-6 shadow-2xl space-y-4"
            >
              <div className="flex justify-between items-center">
                <h3 className="font-display text-lg font-bold text-white">Save Coverage Report</h3>
                <button
                  onClick={() => setShowSaveModal(false)}
                  className="text-text-muted hover:text-white text-lg font-bold"
                >
                  ✕
                </button>
              </div>
              <p className="text-xs text-text-secondary">
                This report will be added to your profile under the "My Coverage Reports" tab. You can add a short note for reference.
              </p>
              <div className="space-y-2">
                <label className="text-[11px] font-bold text-text-secondary uppercase">
                  Notes (Optional)
                </label>
                <textarea
                  value={userNote}
                  onChange={(e) => setUserNote(e.target.value.slice(0, 200))}
                  placeholder="e.g. Draft 2 feedback, focusing on Act 2 rewrite ideas..."
                  className="w-full h-24 bg-[#0d0d12] border border-white/5 rounded-xl p-3 text-xs text-white placeholder-text-muted focus:border-amber/50 outline-none resize-none"
                />
                <div className="text-right text-[10px] text-text-muted">
                  {userNote.length}/200
                </div>
              </div>
              <div className="flex gap-3">
                <button
                  onClick={() => setShowSaveModal(false)}
                  className="flex-1 h-11 rounded-lg border border-white/10 text-xs font-semibold text-text-secondary hover:text-white"
                >
                  Cancel
                </button>
                <button
                  onClick={handleSaveReport}
                  disabled={isSaving}
                  className="flex-1 h-11 rounded-lg bg-amber hover:bg-amber-hover text-surface text-xs font-bold flex items-center justify-center"
                >
                  {isSaving ? "Saving..." : "Save Report"}
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
